/*
 * This file was generated by orbit-idl-2 - DO NOT EDIT!
 */

#include <string.h>
#define ORBIT2_STUBS_API
#define ORBIT_IDL_C_COMMON
#define GNOME_GThumb_COMMON
#include "GNOME_GThumb.h"

static const CORBA_unsigned_long ORBit_zero_int = 0;

#ifndef ORBIT_IDL_C_IMODULE_GNOME_GThumb
void _ORBIT_skel_small_GNOME_GThumb_Application_open_browser(POA_GNOME_GThumb_Application             *_o_servant, gpointer            _o_retval,gpointer           *_o_args,CORBA_Context       _o_ctx,CORBA_Environment  *_o_ev,
void (*_impl_open_browser)(PortableServer_Servant _servant, const CORBA_char * uri, CORBA_Environment *ev)) {
_impl_open_browser (_o_servant, *(const CORBA_char * *)_o_args[0], _o_ev);
}
void _ORBIT_skel_small_GNOME_GThumb_Application_open_viewer(POA_GNOME_GThumb_Application             *_o_servant, gpointer            _o_retval,gpointer           *_o_args,CORBA_Context       _o_ctx,CORBA_Environment  *_o_ev,
void (*_impl_open_viewer)(PortableServer_Servant _servant, const CORBA_char * uri, CORBA_Environment *ev)) {
_impl_open_viewer (_o_servant, *(const CORBA_char * *)_o_args[0], _o_ev);
}
void _ORBIT_skel_small_GNOME_GThumb_Application_load_image(POA_GNOME_GThumb_Application             *_o_servant, gpointer            _o_retval,gpointer           *_o_args,CORBA_Context       _o_ctx,CORBA_Environment  *_o_ev,
void (*_impl_load_image)(PortableServer_Servant _servant, const CORBA_char * uri, CORBA_Environment *ev)) {
_impl_load_image (_o_servant, *(const CORBA_char * *)_o_args[0], _o_ev);
}
void _ORBIT_skel_small_GNOME_GThumb_Application_import_photos(POA_GNOME_GThumb_Application             *_o_servant, gpointer            _o_retval,gpointer           *_o_args,CORBA_Context       _o_ctx,CORBA_Environment  *_o_ev,
void (*_impl_import_photos)(PortableServer_Servant _servant, CORBA_Environment *ev)) {
_impl_import_photos (_o_servant, _o_ev);
}

#endif
#if ( (TC_IMPL_TC_GNOME_GThumb_Application_0 == 'G') \
&& (TC_IMPL_TC_GNOME_GThumb_Application_1 == 'N') \
&& (TC_IMPL_TC_GNOME_GThumb_Application_2 == 'O') \
&& (TC_IMPL_TC_GNOME_GThumb_Application_3 == 'M') \
&& (TC_IMPL_TC_GNOME_GThumb_Application_4 == 'E') \
&& (TC_IMPL_TC_GNOME_GThumb_Application_5 == '_') \
&& (TC_IMPL_TC_GNOME_GThumb_Application_6 == 'G') \
&& (TC_IMPL_TC_GNOME_GThumb_Application_7 == 'T') \
&& (TC_IMPL_TC_GNOME_GThumb_Application_8 == 'h') \
&& (TC_IMPL_TC_GNOME_GThumb_Application_9 == 'u') \
&& (TC_IMPL_TC_GNOME_GThumb_Application_10 == 'm') \
&& (TC_IMPL_TC_GNOME_GThumb_Application_11 == 'b') \
) && !defined(TC_DEF_TC_GNOME_GThumb_Application)
#define TC_DEF_TC_GNOME_GThumb_Application 1
#ifdef ORBIT_IDL_C_IMODULE_GNOME_GThumb
static
#endif
ORBIT2_MAYBE_CONST struct CORBA_TypeCode_struct TC_GNOME_GThumb_Application_struct = {
{&ORBit_TypeCode_epv, ORBIT_REFCOUNT_STATIC},
CORBA_tk_objref,
0,
0,
ORBIT_ALIGNOF_CORBA_POINTER,
0,
0
,
NULL,
CORBA_OBJECT_NIL,
(char *)"Application",
(char *)"IDL:GNOME/GThumb/Application:1.0",
NULL,
NULL,
-1,
0,
0, 0
};
#endif

#ifndef ORBIT_IDL_C_IMODULE_GNOME_GThumb
CORBA_unsigned_long GNOME_GThumb_Application__classid = 0;
#endif

/* Interface type data */

static ORBit_IArg GNOME_GThumb_Application_open_browser__arginfo [] = {
	{ TC_CORBA_string,  ORBit_I_ARG_IN , (char *)"uri" }
};
static ORBit_IArg GNOME_GThumb_Application_open_viewer__arginfo [] = {
	{ TC_CORBA_string,  ORBit_I_ARG_IN , (char *)"uri" }
};
static ORBit_IArg GNOME_GThumb_Application_load_image__arginfo [] = {
	{ TC_CORBA_string,  ORBit_I_ARG_IN , (char *)"uri" }
};

#ifdef ORBIT_IDL_C_IMODULE_GNOME_GThumb
static
#endif
ORBit_IMethod GNOME_GThumb_Application__imethods [] = {
	{
		{ 1, 1, GNOME_GThumb_Application_open_browser__arginfo, FALSE },
		{ 0, 0, NULL, FALSE },
		{ 0, 0, NULL, FALSE },
TC_void, (char *)"open_browser", 12,
		0 | ORBit_I_METHOD_1_WAY
}
, 	{
		{ 1, 1, GNOME_GThumb_Application_open_viewer__arginfo, FALSE },
		{ 0, 0, NULL, FALSE },
		{ 0, 0, NULL, FALSE },
TC_void, (char *)"open_viewer", 11,
		0 | ORBit_I_METHOD_1_WAY
}
, 	{
		{ 1, 1, GNOME_GThumb_Application_load_image__arginfo, FALSE },
		{ 0, 0, NULL, FALSE },
		{ 0, 0, NULL, FALSE },
TC_void, (char *)"load_image", 10,
		0 | ORBit_I_METHOD_1_WAY
}
, 	{
		{ 0, 0, NULL, FALSE },
		{ 0, 0, NULL, FALSE },
		{ 0, 0, NULL, FALSE },
TC_void, (char *)"import_photos", 13,
		0 | ORBit_I_METHOD_1_WAY
}
};

static CORBA_string GNOME_GThumb_Application__base_itypes[] = {
(char *)"IDL:Bonobo/Unknown:1.0",
(char *)"IDL:omg.org/CORBA/Object:1.0"
};
#ifdef ORBIT_IDL_C_IMODULE_GNOME_GThumb
static
#endif
ORBit_IInterface GNOME_GThumb_Application__iinterface = {
TC_GNOME_GThumb_Application,{4, 4, GNOME_GThumb_Application__imethods, FALSE},
{2, 2, GNOME_GThumb_Application__base_itypes, FALSE}
};

