/*
 * This file was generated by orbit-idl-2 - DO NOT EDIT!
 */

#include <string.h>
#define ORBIT2_STUBS_API
#include "GNOME_GThumb.h"

void GNOME_GThumb_Application_open_browser(GNOME_GThumb_Application _obj, const CORBA_char * uri, CORBA_Environment *ev){
gpointer _args[1];
_args[0] = (gpointer)&uri;
ORBit_c_stub_invoke (_obj, &GNOME_GThumb_Application__iinterface.methods, 0, NULL, _args, NULL, ev, GNOME_GThumb_Application__classid, G_STRUCT_OFFSET (POA_GNOME_GThumb_Application__epv, open_browser),
(ORBitSmallSkeleton) _ORBIT_skel_small_GNOME_GThumb_Application_open_browser);

}
void GNOME_GThumb_Application_open_viewer(GNOME_GThumb_Application _obj, const CORBA_char * uri, CORBA_Environment *ev){
gpointer _args[1];
_args[0] = (gpointer)&uri;
ORBit_c_stub_invoke (_obj, &GNOME_GThumb_Application__iinterface.methods, 1, NULL, _args, NULL, ev, GNOME_GThumb_Application__classid, G_STRUCT_OFFSET (POA_GNOME_GThumb_Application__epv, open_viewer),
(ORBitSmallSkeleton) _ORBIT_skel_small_GNOME_GThumb_Application_open_viewer);

}
void GNOME_GThumb_Application_load_image(GNOME_GThumb_Application _obj, const CORBA_char * uri, CORBA_Environment *ev){
gpointer _args[1];
_args[0] = (gpointer)&uri;
ORBit_c_stub_invoke (_obj, &GNOME_GThumb_Application__iinterface.methods, 2, NULL, _args, NULL, ev, GNOME_GThumb_Application__classid, G_STRUCT_OFFSET (POA_GNOME_GThumb_Application__epv, load_image),
(ORBitSmallSkeleton) _ORBIT_skel_small_GNOME_GThumb_Application_load_image);

}
void GNOME_GThumb_Application_import_photos(GNOME_GThumb_Application _obj, CORBA_Environment *ev){
ORBit_c_stub_invoke (_obj, &GNOME_GThumb_Application__iinterface.methods, 3, NULL, NULL, NULL, ev, GNOME_GThumb_Application__classid, G_STRUCT_OFFSET (POA_GNOME_GThumb_Application__epv, import_photos),
(ORBitSmallSkeleton) _ORBIT_skel_small_GNOME_GThumb_Application_import_photos);

}
